name: Build Hugo and Pagefind

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Cấp quyền để Actions có thể push code vào branch của bạn
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo
        run: hugo --minify

      - name: Post-build Pagefind Indexing
        run: |
          npx pagefind --site "docs"

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-build hugo and pagefind [skip ci]"
          branch: main
          file_pattern: 'docs/*' # Chỉ commit những thay đổi trong thư mục docs